[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#176B87"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7F9"
textColor = "#172026"
